version: '3'  # requires Docker Compose 1.13 or later

services:
  
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    hostname: 'rabbitmq'
    environment: 
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    