FROM node:12-alpine

# Create app directory
WORKDIR /usr/src/app

COPY ./src/package*.json ./

RUN npm install 

# Bundle app source
COPY ./src/generateKey.js .
COPY ./src/rabbit.js .

CMD [ "node", "generateKey.js" ]