FROM node:12-alpine

# Create app directory
WORKDIR /usr/src/app

COPY ./src/package*.json ./
COPY ./wait-for-it.sh .
RUN npm install 

# Bundle app source
COPY ./src/generateKey.js .
COPY ./src/rabbit.js .
COPY ./docker/start.sh .
COPY ./src/config.js .

RUN ["chmod", "+x", "start.sh"]
RUN ["chmod", "+x", "wait-for-it.sh"]
CMD [ "./start.sh" ]