FROM node:12-alpine

# Create app directory
WORKDIR /usr/src/app

COPY ./src/package*.json ./

RUN npm install 

# Bundle app source
COPY ./src/generateEmail.js .
COPY ./src/rabbit.js .
COPY ./src/config.js .

CMD [ "node", "generateEmail.js" ]