FROM node:12-alpine

# Create app directory
WORKDIR /usr/src/app

COPY ./src/package*.json ./

RUN npm install 

# Bundle app source
COPY ./src/server.js .
COPY ./src/rabbit.js .

EXPOSE 8080
CMD [ "node", "server.js" ]