FROM node:12-alpine

# Create app directory
WORKDIR /usr/src/app

COPY ./src/package*.json ./

RUN npm install 

# Bundle app source
COPY ./src/generateEmail.js .
COPY ./src/rabbit.js .
COPY ./src/config.js .
COPY ./docker/start.sh .
COPY ./wait-for-it.sh .
RUN ["chmod", "+x", "start.sh"]
RUN ["chmod", "+x", "wait-for-it.sh"]


CMD [ "./start.sh" ]